# .goreleaser.yml
project_name: sandglass
builds:
  - main: cmd/sandglass/main.go
    binary: sandglass
    ldflags: -extldflags "-static" -X main.version={{.Version}} -X main.tag={{.Tag}} -X main.date={{.Date}} -X main.commit={{.Commit}}
    flags: -a -tags netgo
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
  - main: cmd/sandctl/main.go
    binary: sandctl
    ldflags: -extldflags "-static" -X main.version={{.Version}} -X main.tag={{.Tag}} -X main.date={{.Date}} -X main.commit={{.Commit}}
    flags: -a -tags netgo
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64

brew:
  github:
    owner: celrenheit
    name: homebrew-taps

  commit_author:
    name: Celrenheit
    email: celrenheit+github@gmail.com

  folder: Formula

  homepage: "https://github.com/celrenheit/sandglass"

  description: "Sandglass is a distributed, horizontally scalable, persistent, delayed message queue"

dockers:
  - image: celrenheit/sandglass

archive:
  format: tar.gz
  replacements:
    amd64: 64-bit
    darwin: macOS
  files:
    - LICENSE
    - README.md