FROM celrenheit/golang-rocksdb:1.9.1 AS build
LABEL Salim Alami <celrenheit+github@gmail.com>

EXPOSE 8080

RUN wget https://github.com/goreleaser/goreleaser/releases/download/v0.35.4/goreleaser_Linux_arm64.tar.gz && \
    tar -zxvf goreleaser_Linux_arm64.tar.gz && \
    chmod a+x goreleaser && mv goreleaser /usr/bin/goreleaser


WORKDIR $GOPATH/src/github.com/celrenheit/sandglass


COPY . ./

# RUN git checkout -- . && git clean -f -d
