// Code generated by "stringer -type=Level"; DO NOT EDIT.

package logy

import "fmt"

const _Level_name = "FATALINFODEBUG"

var _Level_index = [...]uint8{0, 5, 9, 14}

func (i Level) String() string {
	if i >= Level(len(_Level_index)-1) {
		return fmt.Sprintf("Level(%d)", i)
	}
	return _Level_name[_Level_index[i]:_Level_index[i+1]]
}
